### PR TITLE
Relative url handling and renderer cleanup

### LINKED ISSUE #425: Markdown rendered preview (incl. notebooks) doesn't show images
Here's a screenshot showing our own README, neither the gif using `` syntax, nor a plain png I linked (temporarily, just in my local copy) with `` syntax work:

image

In contrast, this is what the VSCode preview for the same looks like, both of them render (the gif also animates):

image

Technically this is almost a bug, but we can always say that our preview MVP has documented limitations (no images), so I'll be conservative and tag it as an enhancement... Feel free to retag as bug if you want...

** Important update:** this problem is also present in notebooks, not just in the render preview of plain markdown files.  Since rendering images is extremely widely used (including in our own docs), this is now tagged for 0.90 as a parity bug.  Here's an example of [one of our notebooks](https://github.com/ipython/ipython-in-depth/blob/master/examples/IPython%20Kernel/Index.ipynb) rendered in both lab (top) and classic (bottom), showing the broken image in lab:

image

ps - The basic renderer was requested in #226.

### PR DESCRIPTION
**Pull request by blink1073**
Pushes sanitization and relative url handling down to the renderer.  We were not previously sanitizing the Markdown Preview.  
Handles markdown images, links, and `` tags (and inline gifs).
I also verified that we were not attempting to fetch the relative urls before they are resolved.
Note that markdown url handling could be done by overriding the markdown renderer, but we leave that as a follow-on optimization.

Fixes #425.  cf https://github.com/jupyter/jupyterlab/issues/446

relative_path

relative_paths

### CODE REVIEW

File: src/docmanager/context.ts [hunk 1]
```diff
@@ -191,6 +191,14 @@ class Context implements IDocumentContext<IDocumentModel> {
   }
 
   /**
+   * Traverse the DOM hierarchy of a node, translating
+   * relative URLs.
+   */
+  resolveUrls(node: HTMLElement): void {
+    return this._manager.resolveUrls(this._id, node);
```
Comment (sccolbert) [inline src/docmanager/context.ts]: no `return` on void func

**Comment by blink1073** [comment]
Notes: I am going to refactor this so that we pass an interface to the renderer itself, which allows the renderer to optimize how the url translation occurs.

**Comment by blink1073** [comment]
Functionality is done, I need to update the tests and examples.

**Comment by blink1073** [comment]
FYI, @jasongrout, this affects the ipywidgets `IRenderer`.

File: src/docmanager/context.ts [hunk 2]
```diff
@@ -528,6 +535,20 @@ class ContextManager implements IDisposable {
   }
 
   /**
+   * Resolve a relative url to a correct server path.
+   */
+  resolveUrl(id: string, url: string): string {
+    // TODO: use proper url parser here.
+    if (url.indexOf('http') === 0 || url.indexOf('data') === 0) {
```
Comment (afshin) [inline src/docmanager/context.ts]: This should include URLs that begin with `://` as well.

Comment (blink1073) [inline src/docmanager/context.ts]: I'm going to update `jupyter-js-services` to expose the `url.parse` method.

Comment (blink1073) [inline src/docmanager/context.ts]: Let's just check for a colon for now, there are other API changes coming from an upgrade to js-services that should be done in a follow-on PR.

**Comment by afshin** [comment]
👍
