### PR TITLE
Use existing notebook codemirror defaults

### LINKED ISSUE #354: Autoindent not working in the notebook (only 2 spaces are inserted)
Currently, autoindent is only inserting 2 spaces in the notebook, at least for Python, instead of the customary 4. Furthermore, if you type `<tab>` (the natural reflex most people will have to indent), what happens is that a tab is inserted, leading to mixed space/tab code.   

Here's a screenshot of a cell in the same notebook (created in Lab), opened in Lab and in the classic Notebook; the latter highlights control characters so the tab is visible:

image

### PR DESCRIPTION
**Pull request by blink1073**
Fixes #354.

### CODE REVIEW

File: src/notebook/cells/widget.ts [hunk 1]
```diff
@@ -125,7 +125,22 @@ class BaseCellWidget extends Widget {
...
-    this._editor = renderer.createCellEditor(null);
+    this._editor = renderer.createCellEditor({
+      indentUnit: 4,
+      readOnly: false,
+      theme: 'default',
+      extraKeys: {
+        'Cmd-Right': 'goLineRight',
+        'End': 'goLineRight',
+        'Cmd-Left': 'goLineLeft',
+        'Tab': 'indentMore',
```
Comment (jasongrout) [inline src/notebook/cells/widget.ts]: Thank you! I just got hit with this today when I was trying to indent a block of code, and all it kept doing was pulling up the completion widget!
